import { Swiper, SwiperSlide } from "swiper/react"
import { Autoplay, Pagination } from "swiper/modules"
import "swiper/css"
import "swiper/css/effect-fade"
import "swiper/css/pagination"

import lockIcon from "../assets/icons/lock-icon.svg"

export default function CapsuleCarousel() {

  const data = [
  {
    "id": "capsule-001",
    "title": "Bitcoin Will Hit $100K by Q4 2025",
    "creator": "@quantmind.eth",
    "category": "Market Prediction",
    "timestamp": "2025-06-01T14:20:00Z",
    "summary": "A statistical model trained on macroeconomic indicators and on-chain data signals a 70% probability that Bitcoin will reach 100K USD before end of Q4 2025.",
    "tags": ["bitcoin", "crypto", "prediction", "q4"],
    "status": "Private"
  },
  {
    "id": "capsule-002",
    "title": "Mean Reversion on SOL Pairs – 15m Window",
    "creator": "@arbitrage.tez",
    "category": "Trading Strategy",
    "timestamp": "2025-05-24T09:55:00Z",
    "summary": "A high-frequency trading strategy for Solana token pairs using z-score bands on 15-minute windows. Includes performance metrics and model hyperparams.",
    "tags": ["solana", "tradingbot", "hfstrategy"],
    "status": "For Sale"
  },
  {
    "id": "capsule-003",
    "title": "AI-Created Worldbuilding for 'Neo-Terra'",
    "creator": "@synthetica.ai",
    "category": "Creative Blueprint",
    "timestamp": "2025-04-17T21:03:00Z",
    "summary": "A full worldbuilding capsule generated by AI with detailed lore, geopolitics, and character profiles for a post-human planet. Includes 12 prompt chains and 8 story arcs.",
    "tags": ["worldbuilding", "scifi", "promptchain"],
    "status": "Viewable"
  },
  {
    "id": "capsule-004",
    "title": "The Next GPT Leap: Modular Reasoning",
    "creator": "@brainsurgeon",
    "category": "AI Research",
    "timestamp": "2025-06-10T13:11:00Z",
    "summary": "Theory on how future LLMs will evolve toward modular, chain-of-thought reasoning agents. Linked with supporting whitepaper and benchmark test ideas.",
    "tags": ["gpt5", "modularity", "AIresearch"],
    "status": "Private"
  },
  {
    "id": "capsule-005",
    "title": "Web3 UX Principles for 2030",
    "creator": "@dao.design",
    "category": "DAO Curation",
    "timestamp": "2025-06-05T08:47:00Z",
    "summary": "Curated by 19 DAO members. Contains consensus insights on Web3 UX principles, wallet abstraction, and human-centered protocol design.",
    "tags": ["ux", "web3design", "dao"],
    "status": "Public"
  },
  {
    "id": "capsule-006",
    "title": "Zero-Knowledge Proofs in Voting Systems",
    "creator": "@zk.vote",
    "category": "Tech Research",
    "timestamp": "2025-05-29T16:30:00Z",
    "summary": "Proposal and architecture for using zk-SNARKs in decentralized voting systems. Includes threat model and implementation guide.",
    "tags": ["zkp", "voting", "decentralization"],
    "status": "Viewable"
  },
  {
    "id": "capsule-007",
    "title": "How LLMs Could Break Scientific Peer Review",
    "creator": "@futurejournals",
    "category": "AI Theory",
    "timestamp": "2025-06-11T07:05:00Z",
    "summary": "Exploration of how large language models can simulate peer-review feedback loops, potentially automating scientific consensus building.",
    "tags": ["llm", "peerreview", "futureofscience"],
    "status": "Private"
  },
  {
    "id": "capsule-008",
    "title": "Lore Capsule: 'Children of Ash and Light'",
    "creator": "@mythforge",
    "category": "Creative Blueprint",
    "timestamp": "2025-05-22T18:12:00Z",
    "summary": "Dark fantasy universe blueprint including 5 realms, 12 magical laws, and an evolving AI-powered lore engine.",
    "tags": ["fantasy", "worldbuilding", "ai-lore"],
    "status": "For Sale"
  },
  {
    "id": "capsule-009",
    "title": "Prompt Chain: Generate 100 Startup Ideas from Trends",
    "creator": "@promptpilot",
    "category": "Creator Tools",
    "timestamp": "2025-06-03T20:00:00Z",
    "summary": "A meta-prompt chain that generates startup ideas based on real-time trend scraping + market gap simulation.",
    "tags": ["promptengineering", "startup", "ideagen"],
    "status": "Public"
  },
  {
    "id": "capsule-010",
    "title": "Collective Capsule: Climate Prediction Models 2040",
    "creator": "@ecoDAO",
    "category": "Environmental Forecasting",
    "timestamp": "2025-05-26T11:44:00Z",
    "summary": "Curated capsule combining 7 open-source AI models to forecast climate shift impacts up to 2040 across Asia-Pacific.",
    "tags": ["climate", "forecasting", "ai-models", "dao"],
    "status": "Viewable"
  }
  ]

  const capsules = [
    {
      id: "capsule-001",
      title: "Bitcoin Will Hit $100K by Q4 2025",
      creator: "@quantmind.eth",
      price: "1.2 SOL",
    },
    {
      id: "capsule-002",
      title: "Mean Reversion on SOL Pairs – 15m Window",
      creator: "@arbitrage.tez",
      price: "0.75 SOL",
    },
    {
      id: "capsule-003",
      title: "AI-Created Worldbuilding for 'Neo-Terra'",
      creator: "@synthetica.ai",
      price: "2.5 SOL",
    },
    {
      id: "capsule-004",
      title: "The Next GPT Leap: Modular Reasoning",
      creator: "@brainsurgeon",
      price: "1.8 SOL",
    },
    {
      id: "capsule-005",
      title: "Web3 UX Principles for 2030",
      creator: "@dao.design",
      price: "1.0 SOL",
    },
    {
      id: "capsule-006",
      title: "Zero-Knowledge Proofs in Voting Systems",
      creator: "@zk.vote",
      price: "1.6 SOL",
    },
    {
      id: "capsule-007",
      title: "How LLMs Could Break Scientific Peer Review",
      creator: "@futurejournals",
      price: "2.2 SOL",
    },
    {
      id: "capsule-008",
      title: "Lore Capsule: 'Children of Ash and Light'",
      creator: "@mythforge",
      price: "2.0 SOL",
    },
  ];

  const daoData = {
  name: "EcoDAO",
  contributors: 19,
  capsulesCurated: 73,
  description: "EcoDAO curates climate-focused AI insights and forecasts to guide sustainable protocols. Our community verifies and timestamps predictions, models, and policy prompts.",
  recentCapsules: [
    {
      id: "capsule-010",
      title: "Climate Prediction Models 2040",
      timestamp: "2025-05-26",
      summary: "Forecasting climate shift impacts using 7 AI models. Focused on Asia-Pacific.",
    },
    {
      id: "capsule-031",
      title: "Decentralized Water Risk Index",
      timestamp: "2025-06-02",
      summary: "Combining on-chain hydrology data and AI forecasts to build a risk index.",
    },
    {
      id: "capsule-045",
      title: "AI-Driven Forest Loss Mapping",
      timestamp: "2025-06-10",
      summary: "Using satellite + AI to map and verify forest loss in real time.",
    }
  ]
};



  return (
    <div className="max-w-5xl mx-auto mt-20 border border-[#37B7C3] min-h-auto">
      <Swiper
        modules={[Autoplay, Pagination]}
        pagination={{ clickable: true }}
        autoplay={{
          delay: 4000,
          disableOnInteraction: false,
        }}
        speed={800}             // Tambahin ini! (dalam ms)
        spaceBetween={0}
        slidesPerView={1}
        loop={true}
        className="w-full"
      >
        {/* Slide 1 */}
        <SwiperSlide>
          <div className="relative w-full px-6 py-10 overflow-hidden">
            <p className="text-xs text-white/60 absolute top-4 left-4 z-10">Public Marketplace</p>
            <div className="absolute inset-0 z-0 opacity-20  pointer-events-none">
              <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">
                {capsules.map((capsule) => (
                  <div
                    key={capsule.id}
                    className="bg-gray-900 border border-gray-700 rounded-lg p-5 hover:border-blue-500 transition duration-200 flex flex-col justify-between"
                  >
                    <div>
                      <h3 className="text-lg font-semibold mb-1 line-clamp-2">
                        {capsule.title}
                      </h3>
                      <div className="text-sm text-gray-400">{capsule.creator}</div>
                      <div className="text-sm text-gray-300 mt-4">💸 Price: <span className="font-medium text-white">{capsule.price}</span></div>
                    </div>

                    <div className="mt-6 flex gap-2">
                      <button className="w-full bg-blue-600 hover:bg-blue-700 text-white text-sm py-2 rounded-lg">
                        Place Bid
                      </button>
                      <button className="w-full bg-white text-gray-900 hover:bg-gray-200 text-sm py-2 rounded-lg">
                        Offer
                      </button>
                    </div>
                  </div>
                ))}
              </div>
            </div>
            <div className="flex justify-center items-center h-[300px] relative z-10">
              <img
                src={lockIcon}
                alt="lock"
                className="w-[20px] h-[26px] sm:w-[24px] sm:h-[30px] md:w-[28px] md:h-[36px] lg:w-[32px] lg:h-[42px] text-[#3FC4D3]"
              />
              <span className="text-xl sm:text-2xl lg:text-4xl font-bold ml-3">
                COMING SOON
              </span>
            </div>

          </div>
        </SwiperSlide>

        {/* Slide 2 */}
        <SwiperSlide>
          <div className="relative w-full px-6 py-10 overflow-hidden">
            <p className="text-xs text-white/60 absolute top-4 left-4 z-10">Capsule Indexing & Browsing</p>
            <div className="absolute inset-0 z-0 opacity-20 pointer-events-none">
              <table className="min-w-full table-auto border border-gray-700">
              <thead>
                <tr className="bg-gray-800 text-xs uppercase tracking-wider text-gray-400">
                  <th className="px-4 py-3 text-left">Title</th>
                  <th className="px-4 py-3">Creator</th>
                  <th className="px-4 py-3">Category</th>
                  <th className="px-4 py-3">Tags</th>
                  <th className="px-4 py-3">Timestamp</th>
                  <th className="px-4 py-3">Status</th>
                </tr>
              </thead>
              <tbody>
                {data.map((capsule, index) => (
                  <tr
                    key={capsule.id}
                    className="border-t border-gray-700 hover:bg-gray-800 transition"
                  >
                    <td className="px-4 py-3 text-sm font-medium max-w-xs truncate">
                      {capsule.title}
                    </td>
                    <td className="px-4 py-3 text-sm">{capsule.creator}</td>
                    <td className="px-4 py-3 text-sm">{capsule.category}</td>
                    <td className="px-4 py-3 text-sm">
                      <div className="flex flex-wrap gap-1">
                        {capsule.tags.map((tag, i) => (
                          <span
                            key={i}
                            className="bg-blue-700 text-xs px-2 py-0.5 rounded-full"
                          >
                            {tag}
                          </span>
                        ))}
                      </div>
                    </td>
                    <td className="px-4 py-3 text-xs text-gray-400">
                      {new Date(capsule.timestamp).toLocaleString()}
                    </td>
                    <td className="px-4 py-3 text-sm">
                      <span
                        className={`px-2 py-1 rounded-full text-xs font-semibold ${
                          capsule.status === "Private"
                            ? "bg-red-700 text-red-200"
                            : capsule.status === "For Sale"
                            ? "bg-yellow-700 text-yellow-200"
                            : capsule.status === "Viewable"
                            ? "bg-green-700 text-green-200"
                            : "bg-blue-700 text-blue-200"
                        }`}
                      >
                        {capsule.status}
                      </span>
                    </td>
                  </tr>
                ))}
              </tbody>
              </table>
            </div>
            <div className="flex justify-center items-center h-[300px] relative z-10">
              <img
                src={lockIcon}
                alt="lock"
                className="w-[20px] h-[26px] sm:w-[24px] sm:h-[30px] md:w-[28px] md:h-[36px] lg:w-[32px] lg:h-[42px] text-[#3FC4D3]"
              />
              <span className="text-xl sm:text-2xl lg:text-4xl font-bold ml-3">
                COMING SOON
              </span>
            </div>

          </div>
        </SwiperSlide>

        {/* Slide 3 */}
        <SwiperSlide>
          <div className="relative w-full px-6 py-10 overflow-hidden">
            {/* Heading */}
            <p className="text-xs text-white/60 absolute top-4 left-4 z-20">
              DAO Curation Layer
            </p>

            {/* Background DAO section (opacity layer) */}
            <div className="absolute inset-0 z-0 opacity-20 pointer-events-none">
              <section className="w-full bg-gray-950 text-white py-16 px-6 md:px-10">
                <div className="max-w-6xl mx-auto space-y-10">
                  <div className="space-y-4">
                    <h2 className="text-3xl md:text-4xl font-bold">
                      🏛️ DAO Curation Layer: {daoData.name}
                    </h2>
                    <p className="text-gray-300">{daoData.description}</p>
                    <div className="flex flex-wrap gap-6 mt-4 text-sm text-gray-400">
                      <span>👥 {daoData.contributors} contributors</span>
                      <span>🧠 {daoData.capsulesCurated} capsules curated</span>
                    </div>
                  </div>

                  <div className="space-y-6">
                    <h3 className="text-2xl font-semibold">
                      🧩 Latest Curated Capsules
                    </h3>
                    <ul className="grid gap-6 md:grid-cols-2">
                      {daoData.recentCapsules.map((capsule) => (
                        <li
                          key={capsule.id}
                          className="p-5 border border-white/10 rounded-xl bg-white/5 hover:bg-white/10 transition"
                        >
                          <h4 className="text-lg font-medium">{capsule.title}</h4>
                          <p className="text-sm text-gray-400 mt-1">
                            {capsule.timestamp}
                          </p>
                          <p className="text-sm text-gray-300 mt-2">
                            {capsule.summary}
                          </p>
                        </li>
                      ))}
                    </ul>
                  </div>

                  <div className="flex gap-4 mt-8">
                    <button className="bg-green-600 text-white px-5 py-2 rounded-lg hover:bg-green-500 transition">
                      Join {daoData.name}
                    </button>
                    <button className="border border-white px-5 py-2 rounded-lg hover:bg-white hover:text-black transition">
                      View All Capsules
                    </button>
                  </div>
                </div>
              </section>
            </div>

            {/* Foreground layer */}
            <div className="flex justify-center items-center h-[300px] relative z-10">
              <img
                src={lockIcon}
                alt="lock"
                className="w-[20px] h-[26px] sm:w-[24px] sm:h-[30px] md:w-[28px] md:h-[36px] lg:w-[32px] lg:h-[42px] text-[#3FC4D3]"
              />
              <span className="text-xl sm:text-2xl lg:text-4xl font-bold ml-3">
                COMING SOON
              </span>
            </div>
          </div>
        </SwiperSlide>



      </Swiper>
    </div>
  )
}
